"""Renders Sefer's launcher icons: one black letter on white, as Android
adaptive icons with a monochrome layer for themed icons. Each icon names
its letter and the face it's drawn in (subsets in tool/icon/fonts, all
under the SIL Open Font License, from Google Fonts).

    python3 tool/icon/make_icons.py

Needs Pillow. Writes into android/app/src/main/res and assets/icons.
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / 'android/app/src/main/res'
HERE = Path(__file__).parent
HEBREW = HERE / 'NotoSerifHebrew-Medium.ttf'
FONTS = HERE / 'fonts'
ASSETS = ROOT / 'assets/fonts'

# id: (letter, font file). The first is the default icon.
ICONS = {
    'aleph': ('א', HEBREW),
    'bet': ('ב', HEBREW),
    'lamed': ('ל', HEBREW),
    'tav': ('ת', HEBREW),
    'omega': ('Ω', ASSETS / 'GFSDidot-400.ttf'),
    'pe': ('پ', FONTS / 'ArefRuqaa.ttf'),
    'ko': ('ก', FONTS / 'Taviraj.ttf'),
    'de': ('Д', FONTS / 'PlayfairDisplay.ttf'),
    'eszett': ('ß', FONTS / 'PlayfairDisplay.ttf'),
    'eacute': ('É', FONTS / 'PlayfairDisplayItalic.ttf'),
    'q': ('Q', FONTS / 'UnifrakturMaguntia.ttf'),
    'ani': ('ა', ASSETS / 'NotoSerifGeorgian-400.ttf'),
    'hiragana': ('あ', FONTS / 'ShipporiMincho.ttf'),
    'hangul': ('한', FONTS / 'NanumMyeongjo.ttf'),
    'devanagari': ('अ', FONTS / 'TiroDevanagariHindi.ttf'),
}
INK = (0, 0, 0, 255)
PAPER = (255, 255, 255, 255)

# Adaptive icons are 108 dp; launchers show the middle 72 dp and may mask
# it to a circle of 66 dp. The letter's box stays well inside that circle.
DENSITIES = {'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4}
ADAPTIVE_DP = 108
LETTER_DP = 38  # the letter's larger side
LEGACY_DP = 48


def draw_letter(img, letter, box, font_path):
    """Draws [letter] so its ink fills [box] px on its larger side, centred."""
    size = 1000
    font = ImageFont.truetype(str(font_path), size)
    l, t, r, b = font.getbbox(letter)
    scale = box / max(r - l, b - t)
    font = ImageFont.truetype(str(font_path), max(8, round(size * scale)))
    l, t, r, b = font.getbbox(letter)
    w, h = img.size
    x = (w - (r - l)) / 2 - l
    y = (h - (b - t)) / 2 - t
    ImageDraw.Draw(img).text((x, y), letter, font=font, fill=INK)


def render(letter, font, px, box, background):
    # Draw large and scale down for clean edges.
    k = 4
    img = Image.new('RGBA', (px * k, px * k), background)
    draw_letter(img, letter, box * k, font)
    return img.resize((px, px), Image.LANCZOS)


def rounded(img, radius):
    mask = Image.new('L', img.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, img.size[0] - 1, img.size[1] - 1), radius, fill=255)
    out = Image.new('RGBA', img.size, (0, 0, 0, 0))
    out.paste(img, (0, 0), mask)
    return out


def main():
    for i, (name, (letter, font)) in enumerate(ICONS.items()):
        suffix = '' if i == 0 else f'_{name}'
        for d, k in DENSITIES.items():
            folder = RES / f'mipmap-{d}'
            folder.mkdir(parents=True, exist_ok=True)
            # Foreground and monochrome: the letter on transparent.
            fg = render(letter, font, round(ADAPTIVE_DP * k), LETTER_DP * k, (0, 0, 0, 0))
            fg.save(folder / f'ic_launcher{suffix}_foreground.png')
            # Older Android: a white rounded square with the letter.
            px = round(LEGACY_DP * k)
            legacy = render(letter, font, px, LETTER_DP * 0.7 * k, PAPER)
            rounded(legacy, px * 0.22).save(folder / f'ic_launcher{suffix}.png')
        if suffix:
            (RES / 'mipmap-anydpi-v26' / f'ic_launcher{suffix}.xml').write_text(ADAPTIVE.format(suffix=suffix))
        # For the picker in the app.
        (ROOT / 'assets/icons').mkdir(parents=True, exist_ok=True)
        render(letter, font, 192, 92, PAPER).save(ROOT / f'assets/icons/{name}.png')


ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/icon/make_icons.py. The letter doubles as the
     monochrome layer, so themed icons (Android 13+) tint it. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher{suffix}_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher{suffix}_foreground" />
</adaptive-icon>
"""


if __name__ == '__main__':
    main()
